const Data = [
  {
    id: 1,
    title: 'GFG Essential Tee',
    category: 'T-Shirts',
    image:
      'https://media.geeksforgeeks.org/wp-content/uploads/20230823165506/gfg1.png',
    specs: ['100% Cotton', 'Lightweight', 'Breathable knit'],
    features: ['Minimal logo', 'Regular fit', 'Everyday casual'],
    newPrice: 800,
    oldPrice: 1000,
    stars: 4,
    reviewsCount: 289,
    badge: 'Campus Pick',
    accent: 'sage',
    delivery: 'Free delivery by tomorrow',
  },
  {
    id: 2,
    title: 'GFG Utility Pack',
    category: 'Accessories',
    image:
      'https://media.geeksforgeeks.org/wp-content/uploads/20230823165553/gfg2.jpg',
    specs: ['Durable fabric', 'Lightweight frame', 'Daily commute ready'],
    features: ['Bottle pocket', 'Laptop sleeve', 'Weather-resistant'],
    newPrice: 599,
    oldPrice: 999,
    stars: 5,
    reviewsCount: 467,
    badge: 'Best Value',
    accent: 'amber',
    delivery: 'Ships free in 24 hours',
  },
  {
    id: 3,
    title: 'GFG Signature Hoodie',
    category: 'Hoodies',
    image:
      'https://media.geeksforgeeks.org/wp-content/uploads/20230823165623/gfg3.jpg',
    specs: ['Fleece-lined', 'Attached hood', 'Kangaroo pocket'],
    features: ['Elastic cuffs', 'Relaxed fit', 'Unisex style'],
    newPrice: 1299,
    oldPrice: 1999,
    stars: 5,
    reviewsCount: 467,
    badge: 'Top Rated',
    accent: 'coral',
    delivery: 'Limited stock, dispatch today',
  },
  {
    id: 4,
    title: 'GFG Sprint Cap',
    category: 'Accessories',
    image:
      'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80',
    specs: ['Soft twill', 'Adjustable strap', 'Sun-ready brim'],
    features: ['Embroidered front', 'Moisture control', 'Travel friendly'],
    newPrice: 449,
    oldPrice: 699,
    stars: 4,
    reviewsCount: 176,
    badge: 'New Arrival',
    accent: 'sky',
    delivery: 'Free delivery this week',
  },
  {
    id: 5,
    title: 'GFG Studio Overshirt',
    category: 'Shirts',
    image:
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
    specs: ['Layer-ready', 'Button closure', 'Soft brushed finish'],
    features: ['Streetwear fit', 'Muted palette', 'Trans-seasonal'],
    newPrice: 1499,
    oldPrice: 2099,
    stars: 4,
    reviewsCount: 208,
    badge: 'Editor Choice',
    accent: 'slate',
    delivery: 'Express delivery available',
  },
  {
    id: 6,
    title: 'GFG Weekend Joggers',
    category: 'Bottoms',
    image:
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
    specs: ['Stretch blend', 'Tapered cut', 'All-day comfort'],
    features: ['Zip pocket', 'Elastic waist', 'Gym-to-street'],
    newPrice: 999,
    oldPrice: 1399,
    stars: 5,
    reviewsCount: 354,
    badge: 'Fast Selling',
    accent: 'rose',
    delivery: 'Free shipping on this item',
  },
];

export default Data;
